applications:
  - name: breakfast-club-app
    containers:
      - name: data-server 
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/wl-breakfast-club/data_server:v1
      - name: data-collector 
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/wl-breakfast-club/data_collector:v1
