recipeVersion: 1.0.0-alpha.1
applications:
  - name: hackathon-python-app
    containers:
      - name: sample-app 
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/hackathon-2025-python-samples/sample-app:sha-d037f05
  - name: hackathon-database
    containers:
      - name: database
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/hackathon-2025-python-samples/sample-db:sha-d037f05
        volumes:
          - name: data
            path: /var/lib/postgresql/data
            size: 200Mi
            persistent: true
    ports:
      - port: 5432
