recipeVersion: 1.0.0-alpha.1
applications:
  - name: hackathon-python-app
    containers:
      - name: sample-app 
        image: ghcr.io/liciniomendes-vestas/hackathon-2025-python-samples/sample-app:master
  - name: hackathon-database
    containers:
      - name: database
        image: ghcr.io/liciniomendes-vestas/hackathon-2025-python-samples/sample-db:master
        volumes:
          - name: data
            path: /var/lib/postgresql/data
            size: 200Mi
    ports:
      - port: 5432
